In [1]:
import pandas as pd
import numpy as np
import os


In [38]:
os.chdir('c://users//administrator//desktop')

nd = pd.read_csv('news_data.csv',encoding= 'latin')
nd.head()

news_text news_number  \
0  Et tu, Rhody?  A recent editorial in the Provi...   727600136   
1  A recent post in The Farmington Mirror — our...   731714618   
2  President Donald Trump, as he often does while...   731714635   
3  February is Black History Month, and nothing l...   728627182   
4  The snow was so heavy, whipped up by gusting w...   728627443   

        news_type Unnamed: 3  
0  non-propaganda        NaN  
1  non-propaganda        NaN  
2  non-propaganda        NaN  
3  non-propaganda        NaN  
4  non-propaganda        NaN

In [40]:
nd1 = nd.set_index('news_number').drop(['Unnamed: 3'],axis =1)
nd1.shape

(36025, 2)

In [16]:
np.sum(nd1.isna())

news_text     0
news_type    36
dtype: int64

In [49]:
# nd1[pd.isnull(nd1.news_type)]     

len(nd1[pd.isnull(nd1.news_type)])

36

In [48]:
nd2 = nd1.dropna(axis=0)

In [50]:
x = nd2['news_text'] 

y = nd2['news_type']

In [51]:
## SPLITTING

from sklearn.model_selection import train_test_split as tts

x_tr,x_ts,y_tr,y_ts = tts(x,y,test_size = 0.3)


# COUNT VECTORIZER

In [57]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words= 'english')

x_bw_m = cv.fit(x_tr)   ## bag of words


In [58]:
x_tr_tfm = x_bw_m.transform(x_tr)
x_ts_tfm = x_bw_m.transform(x_ts)

# NAIVE BAYES

In [59]:

from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

model = mnb.fit(x_tr_tfm , y_tr)


In [63]:
model.score(x_tr_tfm,y_tr)

0.9481581454429978

In [66]:
from sklearn.metrics import accuracy_score as acs
y_trp = model.predict(x_tr_tfm)
y_tsp = model.predict(x_ts_tfm)
acs(y_ts,y_p),acs(y_tr,y_p1)

(0.9297953135130129, 0.9481581454429978)

In [69]:
from sklearn.metrics import confusion_matrix as cm

confm_ = cm(y_pred=y_tsp,y_true= y_ts,labels=['non-propaganda', 'propaganda'])
confm_

array([[9106,  501],
       [ 257,  933]], dtype=int64)

In [73]:
tn,fp,fn,tp = confm_.ravel()

rec = tp/(tp+fn)
pre = tp/(tp+fp)

F1_nb_cnt = (2*pre*rec)/(pre+rec)
F1_nb_cnt

0.7111280487804877

# DECISION TREE

In [74]:

from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()

model2 = dtc.fit(x_tr_tfm,y_tr)

In [77]:
model2.score(x_ts_tfm,y_ts)

0.9174770769658238

In [78]:
y_tsp = model2.predict(x_ts_tfm)

In [79]:
confm_ = cm(y_pred=y_tsp,y_true= y_ts)
confm_

array([[9191,  416],
       [ 475,  715]], dtype=int64)

In [80]:
tn,fp,fn,tp = confm_.ravel()

rec = tp/(tp+fn)
pre = tp/(tp+fp)

F1_nb_cnt = (2*pre*rec)/(pre+rec)
F1_nb_cnt

0.6161137440758293

# PASSIVE AGGRE

In [82]:
from sklearn.linear_model import PassiveAggressiveClassifier

pac = PassiveAggressiveClassifier(n_iter=50)

model3 = pac.fit(x_tr_tfm, y_tr)

In [84]:
y_tsp = model3.predict(x_ts_tfm)
confm_ = cm(y_pred=y_tsp,y_true= y_ts)
confm_

array([[9360,  247],
       [ 363,  827]], dtype=int64)

In [85]:
tn,fp,fn,tp = confm_.ravel()

rec = tp/(tp+fn)
pre = tp/(tp+fp)

F1_PA = (2*pre*rec)/(pre+rec)
F1_PA

0.730565371024735

# KNN

In [87]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier()

model4 = knn.fit(x_tr_tfm,y_tr)

In [88]:
y_tsp = model4.predict(x_ts_tfm)
confm_ = cm(y_pred=y_tsp,y_true= y_ts)
confm_

array([[8630,  977],
       [1014,  176]], dtype=int64)

In [89]:
tn,fp,fn,tp = confm_.ravel()

rec = tp/(tp+fn)
pre = tp/(tp+fp)

F1_KNN = (2*pre*rec)/(pre+rec)
F1_KNN

0.15023474178403753

# LOGISTIC REG

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

model5 = lr.fit(x_tr_tfm,y_tr)


In [ ]:
y_tsp = model5.predict(x_ts_tfm)
confm_ = cm(y_pred=y_tsp,y_true= y_ts)
confm_

In [ ]:
tn,fp,fn,tp = confm_.ravel()

rec = tp/(tp+fn)
pre = tp/(tp+fp)

F1_KNN = (2*pre*rec)/(pre+rec)
F1_KNN

# RANDOM FOREST